### PR TITLE
Replaced with new emojis

### PR DESCRIPTION
**Pull request by LordFren**

### CODE REVIEW

**Comment by connor4312** [comment]
Build fails :/

**Comment by Antariano** [comment]
The test is very non-descriptive.... I'm gonna guess you missed one? Make sure you have all files listed in the index.json @LordFren

**Comment by Antariano** [comment]
Found it. index.json specifies all letters to be UPPERCASE, you saved them 1f494 instead of 1F494

**Comment by JamyDev** [comment]
I CAN FIX IT!

**Comment by Antariano** [comment]
@connor4312 can you npm run-script build and npm publish?

**Pull request merged**
