### PR TITLE
Add Programming emote pack

### PR DESCRIPTION
**Pull request by 2Cubed**
Including Python, Node, and Java logos!
(These languages were chosen because they have Tetris clients and are the frequently-used languages with regular clients.

### CODE REVIEW

**Comment by ttaylorr** [comment]
:+1:

**Comment by connor4312** [comment]
lgtm

**Comment by JamyDev** [comment]
Apparently there's only 3 programming languages out there. TIL :P

**Comment by 2Cubed** [comment]
@JamyDev Just did the three main ones with Beam clients. Feel free to add more - if nobody else does, I might at some point. :smile:

**Comment by MCProhosting-Matt** [comment]
I have to veto this one for the time being. We may open these sorts of submissions up once we have unlockables.

**Comment by 2Cubed** [comment]
Oh... OK.

**Pull request merged**
