### PR TITLE
Update :beam to use new logo

### PR DESCRIPTION
**Pull request by 2Cubed**

### CODE REVIEW

**Comment by JamyDev** [comment]
Should we keep the old logo as nostalgia? 😃

**Comment by MattJustMatt** [comment]
Thanks for this PR. @JamyDev there's a special Trello card wrt to nostalgia. ;)

**Comment by 2Cubed** [comment]
@JamyDev @MattJustMatt Ooh... how possible would it be to add a new emote with the old logo (`:retro`, maybe?) that's accessible to only, say, people with the Beta badge?

**Comment by SimonSchick** [comment]
I do like that idea.

**Pull request merged**
