### PR TITLE
Add aliases for devil emote

### PR DESCRIPTION
**Pull request by 2Cubed**
}:]

### CODE REVIEW

**Comment by SimonSchick** [comment]
You have an extra comma at the end of your file, which effectively breaks it.

Please use a JSON validator.

**Comment by MattJustMatt** [comment]
Uhh, that's a lot of aliases.

**Comment by SimonSchick** [comment]
To be fair, [this one](http://www.fileformat.info/info/unicode/char/1f636/index.htm) has one more.

We should probably limit the amount of max aliases to prevent bloat tho.

**Comment by 2Cubed** [comment]
Oops, sorry, @SimonSchick! Typo. >_<

**Comment by 2Cubed** [comment]
@MattJustMatt Yeah, it is. You know what WOULD be fantastic... regex support. :smile:

**Comment by SimonSchick** [comment]
RegEx might be simpler, but also slower, keep in mind, if we add hundreds of emoji replaces based on RegEx, it would eventually become slow.

I think it would be best to limit emoji aliases to ~5.

**Comment by MattJustMatt** [comment]
Yeah going to set a hard limit on 2 aliases for third party emote additions.

**Comment by SimonSchick** [comment]
Alright, please remove all but 2 of your aliases @2Cubed.

**Comment by 2Cubed** [comment]
@SimonSchick Done. :)

**Pull request merged**
