### PR TITLE
Add :beam and :cactus

### PR DESCRIPTION
**Pull request by 2Cubed**
Need a :beam emote! \o/
And :cactus: doesn't need any more explanation. :wink:

### CODE REVIEW

**Comment by JamyDev** [comment]
Where did you get the cactus one from?

**Comment by connor4312** [comment]
Imported from Germany?

**Comment by JamyDev** [comment]
We left the one Fahim bought there tho

**Comment by 2Cubed** [comment]
@JamyDev From EmojiOne. :smile: :cactus:

**Comment by 2Cubed** [comment]
@connor4312 Haha!

**Pull request merged**
