### PR TITLE
Add Whoappa as an emote

### PR DESCRIPTION
**Pull request by JamyDev**
This is a nod to our TechCrunch Disrupt victory.

gif

### CODE REVIEW

**Comment by artdude543** [comment]
:+1:

**Comment by 2Cubed** [comment]
:+1:

**Comment by Innectic** [comment]
:+1:

**Comment by RPiAwesomeness** [comment]
:+1:

**Comment by 2Cubed** [comment]
SUCCESS. :smiley:

**Comment by Innectic** [comment]
MERGE HYPE

**Pull request merged**
