### PR TITLE
Added :cacta

### PR DESCRIPTION
**Pull request by Innectic**
Was watching the Level up cast and this was suggested. It's a thing now.

### CODE REVIEW

**Comment by JamyDev** [comment]
Make it :cacta and I'll merge it from @Matt's computer.

**Comment by Innectic** [comment]
Done. @JamyDev

**Comment by Innectic** [comment]
Not sure why that failed...

**Comment by Innectic** [comment]
Fixed the failed build. @JamyDev

**Comment by MattJustMatt** [comment]
Sorry but we're not planning on adding this emote to the platform at the moment. We do plan to have specific packs that can be bought for sparks and it may make sense as part of one of these!

**Pull request closed without merging**
