### PR TITLE
Add :hamster

### PR DESCRIPTION
**Pull request by 2Cubed**
Add :hamster, as requested in #18.
Amazing artwork done by [Queen_Liz](https://beam.pro/Queen_Liz)!

### CODE REVIEW

**Comment by 2Cubed** [comment]
cc: @MattJustMatt

**Comment by MattJustMatt** [comment]
:D

**Comment by MattJustMatt** [comment]
With how small it is it's a little hard to make out what it is. Perhaps maybe without the wheel?

**Comment by 2Cubed** [comment]
@MattJustMatt Updated. Liz works fast! :smile:

**Pull request merged**
