### PR TITLE
Added :stanley

### PR DESCRIPTION
**Pull request by Innectic**
Make sure to put him on your head while writing code!

### CODE REVIEW

**Comment by Antariano** [comment]
awwwww

**Comment by QuirkySquid** [comment]
This is the story of an emote named Stanley.

**Comment by SimonSchick** [comment]
Please make sure the indentations are the same as in the rest of the file.

**Comment by Innectic** [comment]
@SimonSchick It's the same on my fork of it. It's just messed up on the pull it seems

**Comment by connor4312** [comment]
It's mixing spaces and tabs. Four spaces should be used for indentation.

**Comment by SimonSchick** [comment]
It would be very appreciate if you'd fix your indenting so we can merge this.

**Comment by Innectic** [comment]
Apologizes. Wasn't getting any alerts from here.

**Comment by SimonSchick** [comment]
looks good now

**Comment by ttaylorr** [comment]
Merge :+1:

**Comment by 2Cubed** [comment]
cc: @MattJustMatt

**Comment by 2Cubed** [comment]
:heart: @ttaylorr !

**Comment by MattJustMatt** [comment]
Hey guys, I'm extremely sorry about this but there was a mixup here. We're not actually adding new emotes to the site for a little bit so we need to revert this. :(

**Comment by ttaylorr** [comment]
Sorry about that!

**Comment by 2Cubed** [comment]
Aww. :disappointed:

**Pull request merged**
