### PR TITLE
Minecraftia Emoticon Pack

### PR DESCRIPTION
**Pull request by olivervscreeper**
Simple Minecraft emoticon pack with inspired but custom art.

### CODE REVIEW

**Comment by connor4312** [comment]
Hi olivervscreeper, thanks for your interest in contributing. We aren't quite ready to accept community contributions here, but I'll leave this PR open for when we are!

One point of concern is the large file size of your images. It seems that they were converted from bitmaps. This is fine, but the converter used was rather imprecise and generated lots of artifacts and unnecessary markup in the svgs. This would have to be corrected prior to the PR being accepted.

**Comment by olivervscreeper** [comment]
Not a problem! I'm primarily a Java developer- don't suppose there is any chance of early API access so I can make a chatbot for launch?

**Comment by connor4312** [comment]
You can check out our [developers site](https://github.com/MCProHosting/beam-developers) for API documentation. Initially we don't plan to release an accessible means of accessing chat API. Unlike the main site API, which is OAuth based, chat contains unique sets and scopes of permissions that have to be handled a little differently.

However, after release tomorrow you're welcome to examine the chat protocol and attempt to engineer your own bot, so long as it does not violate our terms of service.

**Comment by connor4312** [comment]
@olivervscreeper you may find this useful https://github.com/MCProHosting/beam-chatty

**Pull request closed without merging**
